### ISSUE TITLE
Breaks on data families in GHC 7.8 due to eta-reduction bug

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#1]
```
λ> :set -XTypeFamilies -XTemplateHaskell 
λ> import Language.Haskell.TH.Datatype 
λ> data family Foo a
λ> newtype instance Foo a = MkFoo a
λ> putStrLn $(reifyDatatype 'MkFoo >>= stringE . show)

<interactive>:7:12:
    Impossible free variable: a_1627419361
    In the splice: $(reifyDatatype 'MkFoo >>= stringE . show)
```

This happens due to a GHC 7.8-specific bug that causes eta-reduced type variables in data family instances (such as the `a` in `MkFoo a`) not to appear when you reify them in Template Haskell.

On GHC 7.8.4 (broken):

```
λ> putStrLn $(reify ''Foo >>= stringE . pprint)
data family Ghci1.Foo a_0 :: *
newtype instance Ghci1.Foo = Ghci2.MkFoo a_1
```

On GHC 8.0.2 (working):

```
λ> putStrLn $(reify ''Foo >>= stringE . pprint)
data family Ghci1.Foo a_0 :: *
newtype instance Ghci1.Foo = Ghci2.MkFoo a_1
```

I have a workaround in place that I use in `bifunctors`, `aeson`, and other libraries. I'll look into porting it over to `th-abstraction` as well.

**Comment by glguy** [comment]
Ugh, good catch. Thanks for checking that!

**Comment by glguy** [comment]
This fix handles all of the cases I came up with. Do let me know if I've missed something

**Comment by RyanGlScott** [comment]
Here's one test case that doesn't appear to work on HEAD:

```
$ cabal repl
Preprocessing library th-abstraction-0.1.1.0...
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.5.0.0 ... linking ... done.
Loading package deepseq-1.3.0.2 ... linking ... done.
Loading package containers-0.5.5.1 ... linking ... done.
Loading package pretty-1.1.1.1 ... linking ... done.
Loading package template-haskell ... linking ... done.
[1 of 1] Compiling Language.Haskell.TH.Datatype ( src/Language/Haskell/TH/Datatype.hs, interpreted )
Ok, modules loaded: Language.Haskell.TH.Datatype.
λ> :set -XPolyKinds -XTypeFamilies -XTemplateHaskell 
λ> data family F a (b :: k) 
λ> data instance F Int x = FInt x
λ> putStrLn $(reifyDatatype ''F >>= stringE . show)
λ> putStrLn $(reifyDatatype 'FInt >>= stringE . show)

<interactive>:7:12:
    Impossible free variable: x_1627419189
    In the splice: $(reifyDatatype 'FInt >>= stringE . show)
λ> putStrLn $(reify ''F >>= stringE . pprint)
data family Ghci1.F a_0 (b_1 :: k_2) :: *
data instance Ghci1.F GHC.Prim.* GHC.Types.Int = Ghci2.FInt x_3
```

**Comment by RyanGlScott** [comment]
Ah, and I remember why this case in particular breaks it—Template Haskell is explicitly quantifying the type used to instantiate the kind variable:

```
λ> :set -XPolyKinds -XTypeFamilies -XTemplateHaskell 
λ> data family F a (b :: k) 
λ> data instance F Int x = FInt x
λ> putStrLn $(reify ''F >>= stringE . show)
FamilyI (DataFamilyD Ghci1.F [KindedTV a_6989586621679052882 StarT,KindedTV b_6989586621679052884 (VarT k_6989586621679052883)] (Just StarT)) [DataInstD [] Ghci1.F [ConT GHC.Types.Int,SigT (VarT x_6989586621679052900) StarT] Nothing [NormalC Ghci2.FInt [(Bang NoSourceUnpackedness NoSourceStrictness,VarT x_6989586621679052900)]] []]
```

Notice that we have `DataInstD [] Ghci1.F [ConT GHC.Types.Int,SigT (VarT x_6989586621679052900) ...` here. So we have to not count `Int` in the calculation of how many type variables are missing, or else we'll get a wrong amount.

**Comment by glguy** [comment]
I don't think the problem is that the Int is being counted, is that the kind parameter is listed.

The type constructor parameters are: `[PlainTV a,KindedTV b (VarT k)]`

The actual constructor parameters are: *k* *a* *b* -- because poly kinds lifts the kind parameters to the front.

The listed constructor parameters are: `[ConT GHC.Prim.*,ConT GHC.Types.Int]`

The missing parameter is: `PlainTV x`

So there are two choices:

1. I count that there is one kind parameter and I drop it. this will leave us with: `[ConT Int, VarT x]`
2. I keep the kind parameters and have `[StarT, ConT Int, VarT x]`

Keeping the kind parameter is a bit of a problem because it's not a real parameter so we can't actually apply the type to it, as far as I know, when reconstructing the type.

Dropping the kind parameter is a problem because someone might want to know those. Perhaps I need to add a new record field for kind parameters?

**Comment by RyanGlScott** [comment]
My vote is for the first option. The kind variable is implicitly quantified after all, and trying to infer the order in which implicitly quantified things should go _post facto_ can get quite messy.

**Comment by glguy** [comment]
I think that f19dd385acc150abd60a4572df690e3cc72e748b handles this now

**Comment by RyanGlScott** [comment]
Thanks, @glguy. Unfortunately, there's at least one more corner case that this doesn't work for:

```
λ> data family Poly (a :: k)
λ> data instance Poly (a :: k) = MkPoly
λ> putStrLn $(reifyDatatype 'MkPoly >>= stringE . show)
λ> putStrLn $(reifyDatatype 'MkPoly >>= stringE . show)
DatatypeInfo {datatypeContext = [], datatypeName = Ghci10.Poly, datatypeVars = [], datatypeVariant = DataInstance, datatypeCons = [ConstructorInfo {constructorName = Ghci11.MkPoly, constructorVars = [], constructorContext = [], constructorFields = [], constructorVariant = NormalConstructor}]}
```

It's not listing _anything_ under `datatypeVars`. Something similar happens when you `reify` it:

```
FamilyI (FamilyD DataFam Ghci10.Poly [KindedTV a_1627419820 (VarT k_1627419819)] (Just StarT)) [DataInstD [] Ghci10.Poly [] [NormalC Ghci11.MkPoly []] []]
```
