### ISSUE TITLE
Figure out what to do with `TypeData`

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#100]
GHC 9.6 will feature a new `TypeData` language extension that lets you write things such as:

```hs
type data T = MkT
```

This will define a data type `T` whose constructor `MkT` is only available for use at the type level. Any value-level uses of `MkT` will be rejected.

This is relevant for `th-abstraction` because `T` and `MkT` can be reified like other type and data constructors. There is a question of how we should handle this on the `th-abstraction` side. Things like `T` above are reified not with `DataD`, but with [`TypeDataD`](https://gitlab.haskell.org/ghc/ghc/-/blob/2648c09cd3caefbcb5febd41867347b81cd94e47/libraries/template-haskell/Language/Haskell/TH/Syntax.hs#L2406-2408), so they won't work out of the box with today's `th-abstraction`. The question is: how _should_ we add support for them? Various options enter my mind:

1. Add another data constructor to [`DatatypeVariant`](https://hackage.haskell.org/package/th-abstraction-0.4.5.0/docs/Language-Haskell-TH-Datatype.html#t:DatatypeVariant) for `type data` declarations. Something like:

   ```hs
   data DatatypeVariant
     = Datatype        -- ^ Type declared with @data@
     | Newtype         -- ^ Type declared with @newtype@
     | DataInstance    -- ^ Type declared with @data instance@
     | NewtypeInstance -- ^ Type declared with @newtype instance@
     | TypeData        -- ^ Type declared with @type data@
   ```

   There are good reasons to treat `TypeData` separately from `Datatype`. Unlike other data types, `type data` declarations cannot have record fields, `deriving` clauses, or datatype contexts. Moreover, without some kind of indication that the thing you just reified was declared with `type data`, a downstream library might try to splice in an occurrence of `MkT` at the value level, which would be an error. With this option, however, the library could check if the variant was `TypeData` and emit a better error message that indicates what the problem is.

   The downside to this option is that is would require a major version bump, as we are changing the definition of the `DatatypeVariant` data type. Perhaps we should wait until we have another breaking change, such as the changes that [`TypeAbstractions`](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/9480) will require.
2. Reject `type data` declarations in `th-abstraction` entirely for now until we have proper support for them via option (1). Tough, but fair.
3. Accept `type data` declarations in `th-abstraction` for now, but treat them identically to reifying normal data types (i.e., give them a `DatatypeVariant` of `Datatype`). This would make it impossible to distinguish `type data` declarations from other `data` declarations in `th-abstraction`, but it would allow _some_ useful things to be done with `type data`.

What are your thoughts, @glguy?

**Comment by glguy** [comment]
My first reaction is option 1 is the best. I think it's to be expected that th-abstraction will likely need major bumps when template-haskell gets major bumps. Upper bounds will protect old users and the library should be as useful as possible as new language features appear.
