### ISSUE TITLE
Support for Unlifted/Unboxed types

### ISSUE THREAD

**Issue by TeofilC** [glguy/th-abstraction#102]
I'd like to use this library for one of my projects, but I'd like it to be able to reify unlifted and unboxed data types.

I'd be happy to try to implement support for them.

I think the main change would be to add a `datatypeKind` field to `DatatypeInfo`.

**Comment by TeofilC** [comment]
Oops this is  a duplicate of #78

**Comment by RyanGlScott** [comment]
Indeed, #78 is as far as I got before tripping over design questions. Since I didn't have a pressing need for `datatypeKind` at the time, that's as far as I got. If you have a need for `datatypeKind`, I'd welcome hearing your thoughts about the design in #78.
