### ISSUE TITLE
Build failure with template-haskell-2.21.0.0

### ISSUE THREAD

**Issue by locallycompact** [glguy/th-abstraction#115]
https://gitlab.horizon-haskell.net/package-sets/horizon-core/-/jobs/450081

**Comment by RyanGlScott** [comment]
The build log you link indicates the error comes from `th-abstraction-0.5.0.0`. This is to be expected, as it imposes upper version bounds of `template-haskell < 2.21`, so building that version of the library with `template-haskell-2.21.0.0` isn't supported.

If you want to build `th-abstraction` with `template-haskell-2.21.0.0`, you need to use [`th-abstraction-0.6.0.0`](https://hackage.haskell.org/package/th-abstraction-0.6.0.0).

**Comment by RyanGlScott** [comment]
I'm going to close this per https://github.com/glguy/th-abstraction/issues/115#issuecomment-1751715244, but please re-open if I've overlooked something.
