### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by TeofilC** [glguy/th-abstraction#116]
Hi @RyanGlScott would it be possible to publish a new release? 

I'm keen to use the new `datatypeReturnKind` stuff

**Comment by RyanGlScott** [comment]
Would you be OK waiting until an alpha release of GHC 9.10 is cut? That way, I can do some basic testing, and if there are any additional major API changes that need to go into the next release, I can release them all at once.

**Comment by TeofilC** [comment]
Sounds good!

**Comment by RyanGlScott** [comment]
[GHC 9.10.1-alpha1 has been released](https://discourse.haskell.org/t/ghc-9-10-1-alpha1-is-now-available/9048). Although there were some changes introduced in the version of `template-haskell` that ships with 9.10.1-alpha1, none of them affect the code in `th-abstraction`. Moreover, all of `th-abstraction`'s tests pass with GHC 9.10.1-alpha1, which is an encouraging sign.

I'll plan on cutting a new `th-abstraction` release this weekend.

**Comment by RyanGlScott** [comment]
I've uploaded [`th-abstraction-0.7.0.0`](https://hackage.haskell.org/package/th-abstraction-0.7.0.0) to Hackage, so we can now close this issue. I've also [revised `th-abstraction-0.6.0.0`](https://hackage.haskell.org/package/th-abstraction-0.6.0.0/revisions/) to support building with GHC 9.10, which should hopefully make it easier for other libraries to upgrade to GHC 9.10.

**Comment by TeofilC** [comment]
Thanks!
