### ISSUE TITLE
Improve error messages for reifyDatatype

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#14]
Whenever `reifyDatatype` can't handle something, it will always give the same error message (`Expected a type constructor`). However, there are times when that error is pretty misleading:

```
λ> :set -XTypeFamilies -XTemplateHaskell
λ> putStrLn $(reify ''(->) >>= stringE . show)
PrimTyConI GHC.Prim.(->) 2 False
λ> putStrLn $(reifyDatatype ''(->) >>= stringE . show)

<interactive>:3:12: error:
    • reifyDatatype: Expected a type constructor
    • In the untyped splice: $(reifyDatatype ''(->) >>= stringE . show)
λ> data family Foo
λ> putStrLn $(reify ''Foo >>= stringE . show)
FamilyI (DataFamilyD Ghci2.Foo [] (Just StarT)) []
λ> putStrLn $(reifyDatatype ''Foo >>= stringE . show)

<interactive>:6:12: error:
    • reifyDatatype: Expected a type constructor
    • In the untyped splice: $(reifyDatatype ''Foo >>= stringE . show)
λ> putStrLn $(reify ''Show >>= stringE . show)
ClassI ...
λ> putStrLn $(reifyDatatype ''Show >>= stringE . show)

<interactive>:8:12: error:
    • reifyDatatype: Expected a type constructor
    • In the untyped splice: $(reifyDatatype ''Show >>= stringE . show)
```

All three of these rejected examples are, in fact, type constructors—just not the form of type constructor that `reifyDatatype` expects. We ought to give a more descriptive error message in each case.

**Comment by glguy** [comment]
See

https://github.com/glguy/th-abstraction/blob/ddb923361d77cb6f921a767a8cb0f4990d0f6170/src/Language/Haskell/TH/Datatype.hs#L172-L177

**Comment by RyanGlScott** [comment]
Thanks!

I think one improvement we could make for the error message for `FamilyI` is to mention that you might have meant to supply a data family _instance_ constructor instead of a data family _type_ constructor.

In fact, do we mention anywhere in the docs about this trick? The Haddocks for `reifyDatatype` [don't](https://github.com/glguy/th-abstraction/blob/ddb923361d77cb6f921a767a8cb0f4990d0f6170/src/Language/Haskell/TH/Datatype.hs#L150-L151), at least.

**Comment by glguy** [comment]
I think I covered this with cbac77fbb056d66246762dfbc6b1fa890a9cf6bd
