### ISSUE TITLE
Feature request: reifyConstructor

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#15]
Just as `th-abstraction` currently provides a `reifyDatatype` function, it would be convenient to have a `reifyConstructor` function which provides a normalized view of a `DataConI`. There are a couple of reasons why I'd find this useful:

1. The type signature of `DataConI` changed in `template-haskell-2.11.0.0` (its `Fixity` field was removed). This is the source of a lot of CPP in my TH-related code.
2. There are a number of old TH bugs that manifest when you reify certain constructors. For example, if you reify an unboxed tuple constructor on `template-haskell-2.11.0.0`, you get back a surprising type ([GHC Trac #12403](https://ghc.haskell.org/trac/ghc/ticket/12403)):

   ```
   λ> putStrLn $(reify '(#,#) >>= stringE . show)
   DataConI GHC.Prim.(#,#) (ForallT [KindedTV a_3530822107858468866 (ConT GHC.Types.RuntimeRep),KindedTV b_3530822107858468867 (ConT GHC.Types.RuntimeRep),KindedTV c_3530822107858468868 (AppT (ConT GHC.Prim.TYPE) (VarT a_3530822107858468866)),KindedTV d_3530822107858468869 (AppT (ConT GHC.Prim.TYPE) (VarT b_3530822107858468867))] [] (AppT (AppT ArrowT (VarT c_3530822107858468868)) (AppT (AppT ArrowT (VarT d_3530822107858468869)) (AppT (AppT (TupleT 4) (VarT c_3530822107858468868)) (VarT d_3530822107858468869))))) GHC.Prim.(#,#)
   ```

   Namely, it uses `TupleT` instead of `UnboxedTupleT`, and the arity is `4` instead of `2`. This sort of bug could be worked around in `reifyConstructor`.

**Comment by glguy** [comment]
Currently reifyDatatype supports looking up a type by one of its value constructors. Perhaps we should put this compatibility logic into the existing normalization functions for constructors?

Formatted GHC 8.0.2 output

```haskell
> putStrLn $(stringE . show =<< reifyDatatype ''(#,#))
DatatypeInfo
  { datatypeContext = []
  , datatypeName = GHC.Prim.(#,#)
  , datatypeVars =
      [ SigT (VarT c_3530822107858468868) (AppT (ConT GHC.Prim.TYPE) (VarT a_3530822107858468866))
      , SigT (VarT d_3530822107858468869) (AppT (ConT GHC.Prim.TYPE) (VarT b_3530822107858468867))]
  , datatypeVariant = Datatype
  , datatypeCons =
      [ ConstructorInfo {constructorName = GHC.Prim.(#,#)
      , constructorVars = []
      , constructorContext = []
      , constructorFields = [VarT c_3530822107858468868,VarT d_3530822107858468869]
      , constructorStrictness =
          [ FieldStrictness
              { fieldUnpackedness = UnspecifiedUnpackedness
              , fieldStrictness = UnspecifiedStrictness}
          , FieldStrictness
              { fieldUnpackedness = UnspecifiedUnpackedness
              , fieldStrictness = UnspecifiedStrictness}]
      , constructorVariant = NormalConstructor}]}
```

**Comment by RyanGlScott** [comment]
> Currently reifyDatatype supports looking up a type by one of its value constructors. Perhaps we should put this compatibility logic into the existing normalization functions for constructors?

I've of two minds on this.

On one hand, implementing it the way you propose would provide some nice symmetry between `reifyDatatype` and `reifyConstructor`.

On the other hand, there is some information that `DataConI` gives you that you don't get in `TyConI`:

* If it's a data family instance constructor, `DataConI` gives you the `Name` of the parent data family, which `ConstructorInfo` does not give you (currently).
* `DataConI` also gives you the full type signature of the constructor. `ConstructorInfo` sort of gives you this, as you could reconstruct the type signature yourself from `constructorVars`/`constructorContext`/`constructorFields`... However, the result might look rather different from the `Type` that `DataConI` would give you. For instance, if you had a GADT:

   ```
   data Foo a where
     MkFoo :: b -> Foo b
   ```

   Then the `Type` that `DataConI` would give you would be `b -> Foo b`, whereas the reconstructed `Type` you'd get from `ConstructorInfo` would be `a -> Foo a`. This is only a cosmetic difference, but if you're relying on `reifyConstructor` giving you back the type exactly as the user wrote it, this could matter.

**Comment by glguy** [comment]
If you used `reifyDatatype` on a value constructor and then pulled the matching `ConstructorInfo` out of the result you'd have the parent `Name` and most of the constructor information. Is the only thing missing the original, unmodfied type signature? If so, we might just want to add that as a field on the existing `ConstructorInfo`.

Instead of a separate `reifyConstructor` we might only need a little helper function to extract a `ConstructorInfo` by `Name` from a `DatatypeInfo`

**Comment by RyanGlScott** [comment]
> Is the only thing missing the original, unmodfied type signature?

Yes. Besides the issue of having possibly alpha-renamed type variables, there's another gotcha that I just remembered: you can have type synonyms in a GADT return type! For instance:

```haskell
type Konst a b = a
data T a where
  MkT :: Int -> Konst (T Int) Char
```

Without looking up the type in `DataConI`, there is no way to learn of this use of `Konst`.

> Instead of a separate `reifyConstructor` we might only need a little helper function to extract a `ConstructorInfo` by `Name` from a `DatatypeInfo`

I like the sound of that. If you don't mind beefing up `ConstructorInfo` even more, then we could accomplish all of this without needing a separate interface for the extra bits we get from `DataConI`, which would be slick.
