### ISSUE TITLE
Feature request: reifyFixity'

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#21]
GHC 8.0 and later provides `reifyFixity :: Name -> Q (Maybe Fixity)` to look up fixity. Prior to that, one had to use `reify` and pluck out the fixity from various `Info` constructors. We should provide a function (which I'll propose calling `reifyFixity'`, for lack of a better name) which provides a way to obtain fixity across all GHCs without CPP.

**Comment by glguy** [comment]
Initial support for this feature in

e8f1b0387f792b6d6a7e0c46fdda8fc5c1c7bf3c 

Is there anything more clever than this that we need?

**Comment by RyanGlScott** [comment]
Sorry, I should have been more precise in my original description. To be clear, that's not the type signature I was envisioning. I was thinking:

```haskell
reifiyFixityCompat :: Name -> Q Fixity
```

rather than

```haskell
reifyFixityCompat :: Name -> Q (Maybe Fixity)
```

The problem with the latter signature is that the `Maybe` means different things on different GHCs. On GHC 8.0 and later, 'Just' means "there's a user-specified fixity declaration for this". On GHCs prior to 8.0, however, it means "it's either a `VarI`, `ClassOpI`, or a `DataConI`", as those are the only three forms for which you can look up the fixity. As a result, you could get back `Just` on GHC 7.10 but `Nothing` on GHC 8.0.

I think we should implement it like this:

```haskell
#if MIN_VERSION_template_haskell(2,11,0)
reifyFixityCompat = fromMaybe defaultFixity <$> reifyFixity
#else
reifyFixityCompat =
  do info <- reify n
     return $! case info of
       ClassOpI _ _ _ fixity -> fixity
       DataConI _ _ _ fixity -> fixity
       VarI     _ _ _ fixity -> fixity
       _                     -> defaultFixity
#endif
```

With the concession that on older GHCs, you'll always get `defaultFixity` for things that aren't functions, class methods, or data constructors.

**Comment by glguy** [comment]
I would think that deciding whether to fallback to defaultFixity when unsure would be something that the user would do when using th-abstraction. Baking this into the compatibility function would hide when the answer was wrong from the user.

**Comment by glguy** [comment]
Or is it the case that whenever one GHC would return Nothing that the other would return defaultFixity?

**Comment by RyanGlScott** [comment]
> Or is it the case that whenever one GHC would return Nothing that the other would return defaultFixity?

Yes. On GHC 8.0.2:

```
λ> putStrLn $(reifyFixityCompat 'False >>= stringE . show)
Nothing
```

On GHC 7.10.3:

```
λ> putStrLn $(reifyFixityCompat 'False >>= stringE . show)
Just (Fixity 9 InfixL)
```

**Comment by glguy** [comment]
@RyanGlScott But then on older GHCs the answer will be wrong for type operators?

**Comment by RyanGlScott** [comment]
> But then on older GHCs the answer will be wrong for type operators?

Yes, that is true. But the answer for type operators on old GHCs will be wrong in some sense regardless of which approach we pick. If we go with the way `reifyFixityCompat` is currently implemented, the fixity for type operators will always be `Nothing` on old GHCs, even if there is a fixity declaration for that operator. If we go with my proposal, `reifyFixityCompat` will always give `Just defaultFixity` for type operators on old GHCs (again, for the same reasons).

I could go either way on how to implement this, but we should definitely note the gotchas regardless of which approach we adopt.

**Comment by RyanGlScott** [comment]
Here's a third approach to implementing this. As noted in https://github.com/glguy/th-abstraction/issues/21#issuecomment-305991173, `Just fixity` represents two different concepts in GHC 7.10.3 and 8.0.2. We could paper over this issue by making the `Just` _also_ mean "we were able to find a fixity". We can do so with this implementation:

```haskell
#if MIN_VERSION_template_haskell(2,11,0)
reifyFixityCompat = reifyFixity <|> Just defaultFixity
#else
reifyFixityCompat =
  do info <- reify n
     return $! case info of
       ClassOpI _ _ _ fixity -> Just fixity
       DataConI _ _ _ fixity -> Just fixity
       VarI     _ _ _ fixity -> Just fixity
       _                     -> Nothing
#endif
```

Notice that on GHC 8.0 or later, it will _always_ return `Just` a fixity. On GHC 7.10.3, it will only return `Nothing` if it lacks the ability to look up the fixity for that construct (e.g., type operators). This way, we can accurately claim that `reifyFixityCompat` behaves uniformly across all GHCs, with the caveat that it might give you `Nothing` on old GHCs.

Does that sound agreeable?

**Comment by glguy** [comment]
I like this. It means that `Just` indicates a known, correct answer, and `Nothing` indicates an unknown answer.
