### ISSUE TITLE
Consider using the BSD license

### ISSUE THREAD

**Issue by ndmitchell** [glguy/th-abstraction#29]
Almost all code on Hackage is licensed under BSD - which makes exercises like license compliance easier. Do you feel strongly about using ISC? I was actually a little surprised that it was listed as valid on Hackage, since I'd never heard of it.

**Comment by glguy** [comment]
ISC is the replacement for the legacy MIT and BSD licenses, and is used by default by npm and OpenBSD. I'd like to see more projects moving to its simpler language that to continue using university-themed licenses because of inertia. It is OSI approved and listed by FSF as compatible with GPL.

**Comment by ndmitchell** [comment]
Thanks for the info - happy to do the necessary work if it's a better license and likely to crop up more and more over time.
