### ISSUE TITLE
Feature request: reifying record selectors

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#31]
While looking at https://github.com/ekmett/lens/issues/710, it occurred to me that it would be convenient to look up the `ConstructorInfo` for a record selector's constructor by simply giving the record's `Name`. Accomplishing this requires more boilerplate than one might expect. For instance, if you try reifying a simple record, this is all you get:

```haskell
λ> data Foo = MkFoo { runFoo :: Int }
λ> putStrLn $(reify 'runFoo >>= stringE . ppShow)
VarI
  Ghci4.runFoo
  (AppT (AppT ArrowT (ConT Ghci4.Foo)) (ConT GHC.Types.Int))
  Nothing
```

To actually retrieve the `ConstructorInfo` from this, you'd need to decompose the type to extract the `Foo` `Type`, and then reify _that_. This sounds like the purview of `th-abstraction`.

A design question: should this be its own `reifyRecord` function? Or should we augment `reifyDatatype`/[`reifyConstructor`](https://github.com/glguy/th-abstraction/issues/15) to be able to accept record `Name`s?

**Comment by RyanGlScott** [comment]
Actually, this is not at all as easy as I'm making it out to be. Doing the actual datatype lookup becomes significantly more challenging once you throw data families into the mix. For instance, here's a brainteaser:

```
λ> data family Wat (a :: k)
λ> data instance Wat (f a :: *) where MkWat :: { getWat :: Int} -> Wat (Maybe Int)
VarI
  Ghci2.getWat
  (AppT
     (AppT
        ArrowT
        (AppT
           (ConT Ghci1.Wat)
           (AppT (ConT GHC.Base.Maybe) (ConT GHC.Types.Int))))
     (ConT GHC.Types.Int))
  Nothing
```

Reifying `getWat` only gives you the type `Wat (Maybe Int)`, and now we have the task of finding a way to link that to `(f a :: *)`. This sounds an awful lot like type/kind inference, which I am loathe to implement in Template Haskell.

I see two possible approaches:

1. We disallow record lookups for data families entirely. Tough, but fair.
2. We use the [`reifyInstances`](http://hackage.haskell.org/package/template-haskell-2.11.1.0/docs/Language-Haskell-TH-Syntax.html#v:reifyInstances) function (which thankfully has existed in every version of Template Haskell that supports looking up data family instances, AFAICT). For instance, this appears to work well in the example above:

   ```
   λ> putStrLn $([t| Maybe Int |] >>= \t -> reifyInstances ''Wat [t] >>= stringE . ppShow)
   [ DataInstD
       []
       Ghci1.Wat
       [ SigT
           (AppT (VarT f_6989586621679015505) (VarT a_6989586621679015506))
           StarT
       ]
       Nothing
       [ RecGadtC
           [ Ghci2.MkWat ]
           [ ( Ghci2.getWat
             , Bang NoSourceUnpackedness NoSourceStrictness
             , ConT GHC.Types.Int
             )
           ]
           (AppT
              (ConT Ghci1.Wat) (AppT (ConT GHC.Base.Maybe) (ConT GHC.Types.Int)))
       ]
       []
   ]
   ```

**Comment by RyanGlScott** [comment]
If we _did_ pursue option 2, we'd definitely need to make a note of the various bugs that have existing in `reifyInstances`'s history, such as [its inability to look up instances with free variables](https://ghc.haskell.org/trac/ghc/ticket/9262) until GHC 7.10, or [its inability to reason about polykinded data families](https://ghc.haskell.org/trac/ghc/ticket/7477) until GHC 7.8.

**Comment by RyanGlScott** [comment]
Bah, please ignore what I wrote in https://github.com/glguy/th-abstraction/issues/31#issuecomment-310910890 and https://github.com/glguy/th-abstraction/issues/31#issuecomment-310911472. We don't need to do any fancy `reifyInstances` footwork at all. Rather, all we need to do is grab the outermost type constructor (e.g., `Wat` in the example in https://github.com/glguy/th-abstraction/issues/31#issuecomment-310910890), pass that to `reifyDatatype`, check if any of the returned data family instances contain that record—if so, use that data family instance.

**Comment by glguy** [comment]
Nice catch going back through the type constructor to find the matching instance.
