### ISSUE TITLE
reifyDatatype thinks a kind variable is existentially quantified when it isn't

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#37]
```
λ> :set -XPolyKinds -XGADTs
λ> data Eq a b where Refl :: Eq a a
λ> putStrLn $(reifyDatatype ''Eq >>= stringE . ppShow)
DatatypeInfo
  { datatypeContext = []
  , datatypeName = Ghci8.Eq
  , datatypeVars =
      [ SigT (VarT a_6989586621679045063) (VarT k_6989586621679045067)
      , SigT (VarT b_6989586621679045064) (VarT k_6989586621679045067)
      ]
  , datatypeVariant = Datatype
  , datatypeCons =
      [ ConstructorInfo
          { constructorName = Ghci8.Refl
          , constructorVars = [ KindedTV k_6989586621679045071 StarT ]
          , constructorContext =
              [ AppT
                  (AppT EqualityT (VarT a_6989586621679045063))
                  (VarT b_6989586621679045064)
              ]
          , constructorFields = []
          , constructorStrictness = []
          , constructorVariant = NormalConstructor
          }
      ]
  }
```

The kind `k_6989586621679045071` shouldn't be in `constructorVars`, as it's not existentially quantified.

**Comment by glguy** [comment]
Is this new behavior? I'd swear I tested this case earlier. (But maybe I'm misremembering)

**Comment by RyanGlScott** [comment]
I just tried this program on all old releases of `th-abstraction` with GHC 8.0.2, and I get the same `constructorVars` each time, so I don't think this is a regression.

**Comment by RyanGlScott** [comment]
It is worth noting that this only happens with GHC 8.0 and later, since that was when `GadtC` was introduced (which I believe is the culprit here).

**Comment by glguy** [comment]
Oh, I probably didn't try it with PolyKinds.

**Comment by RyanGlScott** [comment]
Ah, I see why this is happening. It's due to [this line](https://github.com/glguy/th-abstraction/blob/53b632625ffd438014a0844bb9afc9fc7c911c5f/src/Language/Haskell/TH/Datatype.hs#L887):

```haskell
tyvars' = [ tv | tv <- tyvars, Map.notMember (tvName tv) subst ]
```

This filters out the non-existentially quantified tyvars by consulting `subst`, which maps constructor-bound tyvars to datatype-bound ones. But `k` manages to sneak through here since it's quantified by the constructor, but does not appear anywhere in `subst`.

It seems that to make this work, we'd need to also filter out any occurrences of the _kinds_ of the vars in `subst`.

**Comment by RyanGlScott** [comment]
I have a `T37` branch which I believe fixes this issue. I'm waiting for #49 to land first before I can make tests for it, since I'll need to use the test suite harness improvements that I added in that patch.
