### ISSUE TITLE
applySubstitution is not capture-avoiding

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#42]
That is, it's possible to substitute into a `ForallT` and end up with something that binds more variables than it should:

```
λ> let a = mkName "a"; b = mkName "b"
λ> let origTy = ForallT [PlainTV a] [] (VarT b)
λ> origTy
ForallT [PlainTV a] [] (VarT b)
λ> applySubstitution (Map.singleton b (VarT a)) origTy
ForallT [PlainTV a] [] (VarT a)
```

**Comment by glguy** [comment]
What behavior would you have expected?

**Comment by RyanGlScott** [comment]
> I knew about this when I wrote it but I don't believe that it's an issue in its current form the way it's being used.

Indeed, it's perhaps not as huge of an issue as it would otherwise be since we're typically dealing with gensym'd variable names everywhere in Template Haskell. Moreover, I hadn't thought about the fact that fixing this (in an efficient way) would basically force `applySubstitution` to live in `Quasi`, which is awkward...

I suppose we could just advertise the fact that `applySubstitution` isn't capture-avoiding and be done with it. Still, this problem has actually bitten us in the past (see #36), and I'm not sure whether the solution is to change `applySubstitution` or to warn people to be more careful when using it.

**Comment by RyanGlScott** [comment]
As it turns out, it may be possible to make it capture-avoiding and keep the pure type signature. The `th-expand-syns` library accomplishes this with an [`evade`](https://github.com/DanielSchuessler/th-expand-syns/blob/0a9420c9fe60c038f72a17cc262f30e09e56c9d5/Language/Haskell/TH/ExpandSyns.hs#L411-L423) function which comes up with a type variable `Name` that isn't in the range of the substitution.

**Comment by RyanGlScott** [comment]
I find myself adding more and more things that _aren't_ capture-avoiding. (Most recently, `substTyVarBndrs` in #49.) In light of this, I'm inclined to just advertise that `applySubstitution` is not capture-avoiding and be done with it.
