### ISSUE TITLE
normalizeDec falls over on a simple GADT

### ISSUE THREAD

**Issue by RyanGlScott** [glguy/th-abstraction#43]
```
λ> putStrLn $([d| data Foo where MkFoo :: Foo |] >>= \[d@DataD{}] -> normalizeDec d >>= stringE . show)

<interactive>:12:12: error:
    • resolveTypeSynonyms: Cannot reify type synonym information
    • In the untyped splice:
        $([d| data Foo where MkFoo :: Foo |]
            >>= \ [d@DataD {}] -> normalizeDec d >>= stringE . show)
```

Most likely, this is because [we call `resolveTypeSynonyms`](https://github.com/glguy/th-abstraction/blob/0754bc97a5aed3f719998b07027eeb8f3f187f70/src/Language/Haskell/TH/Datatype.hs#L908) on GADT return types in `normalizeGadtC`, but in this scenario, `Foo` can't be looked up via `reify`.

**Comment by glguy** [comment]
What's the use-case for using these functions on hand-made declarations? Is this something you're relying on in your other packages?

**Comment by RyanGlScott** [comment]
I encountered this bug when trying to call `declareLenses` on a GADT-style data type. Granted, there is a workaround in this case (use `makeLenses`, which reifies the data type definition instead), but it is slightly annoying that the machinery in this library is completely unusable for any GADT `Dec` due to this issue.

That being said, I'm not sure how one would fix this, aside from going the `th-desugar` route of local reification (which is quite [heavy](https://github.com/goldfirere/th-desugar/blob/afeab520b3300fb1b79f6390dbf0741223d5de67/Language/Haskell/TH/Desugar/Reify.hs)).

**Comment by glguy** [comment]
Perhaps the only solution is to carry around a boolean flag about whether or not it's safe to query the compiler about names in the type. When someone's using newly hand-made declarations we can disable all queries. In the case of GADTs we would disable type synonym resolution and any fixes that relied on this.

**Comment by RyanGlScott** [comment]
I partially agree, but I don't think we need to disable type synonym resolution entirely for hand-made declarations. After all, the root of the issue here is the self-reference to `Foo` in `Foo`'s constructor. I don't see any reason why we need to rule out things like `[d| data Bar where MkBar :: String -> Bar |]`—TH is perfectly capable of resolving the `String` type synonym here, since it's defined in another module.

My hunch is that we can get quite far by adding a special case for self-occurrences of data types in constructor type signatures when resolving type synonyms. We'd still fail on other locally defined types, of course, but let's not let perfect be the enemy of good.
