### ISSUE TITLE
Release version that works with GHC 8.10

### ISSUE THREAD

**Issue by ndmitchell** [glguy/th-abstraction#77]
This package doesn't work with 8.10 pre release and blocks all my testing of everything since it somehow ends up as a dependency of my toolchain. A release with the 8.10 fixes would be great.

**Comment by RyanGlScott** [comment]
Can you clarify what you mean by "doesn't work"? I ask since I've been using `th-abstraction-0.3.1.0-r1` with GHC 8.10.1-alpha1 without issue, so I'm unclear on what issue you are running into.

**Comment by ndmitchell** [comment]
Apologies, I think my CI jobs for 8.10.1-alpha1 have somehow grabbed 8.8.1-alpha1. Now idea how that happened. Sorry for the noise.

**Comment by RyanGlScott** [comment]
In that case, I'll opt to close this issue.
