### ISSUE TITLE
Add an aliases for the Code newtype for typed splices

### ISSUE THREAD

**Issue by anka-213** [glguy/th-abstraction#90]
See this proposal: https://github.com/ghc-proposals/ghc-proposals/pull/195

In ghc-9.0.1 any typed splices should be of the type `CodeQ a` instead of `TExp Q a`.
Something like this should work (but probably with a different names so we don't need to import qualified)

```haskell
-- Compatability layer for Code
liftCode :: TH.TExpQ a -> CodeQ a
examineCode :: CodeQ a -> TH.TExpQ a
#if MIN_VERSION_template_haskell(2,17,0)
type CodeQ = TH.CodeQ
liftCode = TH.liftCode
examineCode = TH.examineCode
#else
type CodeQ x = TH.TExpQ x
liftCode = id
examineCode = id
#endif
```
or more polymorphically
```haskell
liftCode :: m (TH.TExp a) -> Code m a
examineCode :: Code m a -> m (TH.TExp a)
#if MIN_VERSION_template_haskell(2,17,0)
type Code = TH.Code
liftCode = TH.liftCode
examineCode = TH.examineCode
#else
type Code m x = m (TH.TExp x)
liftCode = id
examineCode = id
#endif
```

I might send a pull request soon.

**Comment by RyanGlScott** [comment]
I don't necessarily object to the idea of putting these in `th-abstraction` on face value, but at the same time, none of the code in `th-abstraction` uses typed TH, so it's a bit of a loose fit.

Would the [`th-compat`](http://hackage.haskell.org/package/th-compat) library serve your needs? In particular, what you call `Code`, `CodeQ`, `liftCode`, and `examineCode` are referred to as `Splice`, `SpliceQ`, `liftSplice`, and `examineSplice` in `th-compat`. (It also backports versions of these functions that always use `Code`.)

**Comment by anka-213** [comment]
Oh, right that seems perfect. I had missed that package. I found this package since it contains a similar compatibility layer for Names

**Comment by RyanGlScott** [comment]
OK. In that case, I'll close this issue, but please re-open if there is something left unaddressed.
